---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mikus_origin-ingress
spec:
  # ingressClassName: cloudflare-tunnel
  rules:
  - host: "https://mikusorigin.com/"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mo-svc
            port:
              number: 80